### ISSUE TITLE
Error 'Table' object has no attribute 'On'

### ISSUE THREAD

**Issue by tarun29061990** [pglass/sqlitis#14]
sqlitis 'select * from payments inner join invoices on invoices.payment_id == payments.id where invoices.month=="december"'

Please help

**Comment by pglass** [comment]
Yep, this is a bug: `sqlitis` understands "join" but not "inner join"

The double equals (`==`) operator is is invalid SQL, though. Always use a single `=` sign for equality comparisons in SQL.

Correcting the double equals sign and changing the "inner join" to a plain "join" works (this should give you an idea of the equivalent sqlalchemy expression for an inner join):

```bash
$ sqlitis 'select * from payments join invoices on invoices.payment_id = payments.id where invoices.month = "december"'
select([payments.join(invoices, invoices.c.payment_id == payments.c.id)])
```

But using "inner join", outputs the error (this is a bug)

```bash
$ sqlitis 'select * from payments inner join invoices on invoices.payment_id = payments.id where invoices.month = "december"'
'Table' object has no attribute 'On'
```
