### ISSUE TITLE
'NoneType' object has no attribute 'Join'

### ISSUE THREAD

**Issue by melv1n** [pglass/sqlitis#19]
I've got a query with multiple joins. The query looks like this in SQL:

```
SELECT
    user.id,
    task.id,
    user.username,
    task.task_name
FROM user
JOIN user_has_task ON user.id = user_has_task.user_id
JOIN task ON task.id = user_has_task.task_id
```

I've verified that this query works and is valid. Now when I try to convert it, I'll get:

```
sqlitis 'select user.id, task.id, user.username, task.task_name from user join user_has_task on user.id = user_has_task.user_id join task on task.id = user_has_task.task_id'
'NoneType' object has no attribute 'Join'
```

Am I doing something wrong or is it a bug?

**Comment by pglass** [comment]
Thanks for the bug report!

There's probably two bugs here.

#### First bug: some problem handling the table name within the `on` clause

Possibly the same error occurs when dropping the second join, 

```bash
$ sqlitis 'select user.id, task.id, user.username, task.task_name from user join user_has_task on user.id = user_has_task.user_id'
'NoneType' object has no attribute 'Join'

$ sqlitis 'select * from user join user_has_task on user.id = user_has_task.user_id'
'NoneType' object has no attribute 'Join'
```

Yet, when renaming tables (`user -> foo` and `user_has_task -> bar`), I don't see the issue. Which is interesting.

```bash
$ sqlitis 'select * from foo join bar on foo.id = bar.user_id'
select([foo.join(bar, foo.c.id == bar.c.user_id)])
```

#### Second bug: Multiple joins with `on` clauses

A simple multi-join works,

```bash
$ sqlitis 'select * from foo join bar join wumbo'
select([foo.join(bar).join(wumbo)])
```

I've got [at least one test case](https://github.com/pglass/sqlitis/blob/master/tests/data.yaml#L47-L49) for this.

But joins with conditions (`on` clauses) isn't handled right.

```bash
$ sqlitis 'select * from foo join bar on foo.id = bar.foo_id join wumbo on wumbo.id = bar.wumbo_id'
'Table' object has no attribute 'On'
```

**Comment by pglass** [comment]
@melv1n One issue here is that `user` is a keyword in some dialects of sql, so [sqlparse](https://github.com/andialbrecht/sqlparse) (which sqlitis uses for tokenization) is detecting `user` as a keyword rather than an identifier which botches up the conversion. 

For example, I'll get the error with a simple join because `user` is parsed as a keyword.

```bash
$ sqlitis 'select * from user join bar'
'NoneType' object has no attribute 'Join'
```

Whether `user` is a reserved or non-reserved keyword varies across sql dialects[1], but I need to be compatible with sqlparse which treats user as a keyword, so in this case **sqlitis is going to require `user` be quoted**, as follows:

```bash
$ sqlitis 'select * from `user` join bar'
select([`user`.join(bar)])
```

Note that the above is the current output which is invalid Python (due to the backticks) which I'll need to correct as part of a fix for this issue.

---

1. In some dialects (like [T-SQL](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017)) `user` is reserved, meaning it must be quoted when used as a table name. In other dialects (like [MySQL](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-U), user is a keyword but is not reserved and therefore does not need quotes when used as a table name.

**Comment by melv1n** [comment]
I think user is a pretty common table name in a lot of schemas. Wouldn't it be more common for most devs to be referring to an identifier instead of a sql keyword (and therefor it shouldn't be interpreted as a keyword by default)?

**Comment by pglass** [comment]
Well, it's not up to us to decide whether it's a keyword or an identifier. It's part of the sql grammar(s). In real world queries, you have to quote reserved keywords when using them as table names, so I would like this library to work similarly.

**Comment by melv1n** [comment]
Fair enough. I agree being opinionated is not best practice. I still get stuck on the ' joins with conditions (on clauses)'. Any way to get around that one or need to wait for a fix?

**Comment by pglass** [comment]
Hey @melv1n, I just merged a PR with fixes for this issue. I made a release ([v0.0.3](https://pypi.org/project/sqlitis/0.0.3/)). Summary below, but let me know if this doesn't completely fix the issues outlined here and we can reopen (added tests, but they're a little light I think).

Your original, unmodified query will now output an error on the keyword and suggest quotes,

```
$ sqlitis 'select user.id, task.id, user.username, task.task_name from user join user_has_task on user.id = user_has_task.user_id join task on task.id = user_has_task.task_id'
Unexpected keyword 'USER'. Maybe you need to quote: `USER`?
```

(the error message is currently tailored for this type of keyword/identifier issue. Not sure how it fairs in other situations)

And the "fixed" query, with `user` quoted, now works (multiple joins and all).

```
$ sqlitis 'select user.id, task.id, user.username, task.task_name from `user` join user_has_task on user.id = user_has_task.user_id join task on task.id = user_has_task.task_id'
select([user.c.id, task.c.id, user.c.username, task.c.task_name]).select_from(user.join(user_has_task, user.c.id == user_has_task.c.user_id).join(task, task.c.id == user_has_task.c.task_id))
```

You can also put quotes on all table / column names now (which is ugly but good practice),

```
$ sqlitis 'select `user`.`id`, `task`.`id`, `user`.`username`, `task`.`task_name` from `user` join user_has_task on user.id = user_has_task.user_id join task on task.id = user_has_task.task_id'
select([user.c.id, task.c.id, user.c.username, task.c.task_name]).select_from(user.join(user_has_task, user.c.id == user_has_task.c.user_id).join(task, task.c.id == user_has_task.c.task_id))
```

**Comment by melv1n** [comment]
@pglass I've upgraded and it seems to work now. Many thanks for your support and fixing it on such short notice!
