### ISSUE TITLE
 Failed to convert SQL

### ISSUE THREAD

**Issue by Mohitkumar6122** [pglass/sqlitis#40]
After Installing sqlitis. 
When I gave the command <br>
```
sqlitis 'select foo.name, bar.value from foo join bar'
```
<hr>
I am getting the following error  <br>

```
ERROR: Failed to convert SQL: 'select foo.name, bar.value from foo join bar'
'NoneType' object has no attribute 'render'
```
<br> 
Could this be a problem on my side or sqlitis is not working as it is described in the documentation?

**Comment by pglass** [comment]
Hi @Mohitkumar6122, I'm not able to reproduce this myself.

```
$ sqlitis 'select foo.name, bar.value from foo join bar'
select([foo.c.name, bar.c.value]).select_from(foo.join(bar))
```

@Mohitkumar6122 If you are on Windows, Command Prompt does not understand single-quotes as string delimiters. You must use double quotes as follows (or switch to a shell that understands single quotes, like PowerShell)

```
sqlitis "select foo.name, bar.value from foo join bar"
```

Let me know if that does not work for you.

**Comment by Mohitkumar6122** [comment]
@pglass Thanks for the information .
It works fine now!
